user:
  prefix: /
  resource: "user.yaml"

scheduler:
  prefix:
    en: /schedule/
    nl: /schema/
  resource: "scheduler.yaml"

manual_page:
  path: /manual
  defaults: { _controller: App\Controller\ManualController:manualPage }
  methods: [GET]

start_stream:
  path: /stream/start
  defaults: { _controller: App\Controller\LivestreamController:startStream }
  methods: [POST]

stop_stream:
  path: /stream/stop
  defaults: { _controller: App\Controller\LivestreamController:stopStream }
  methods: [POST]

reset_stream:
  path: /stream/reset
  defaults: { _controller: App\Controller\LivestreamController:resetFromFailure }
  methods: [POST]
