parameters:
    app.locales: 'en|nl'
    locale: 'en'
    mailer_user: 'some@mail.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    FOS\UserBundle\Controller\RegistrationController:
        arguments:
            $formFactory: '@fos_user.registration.form.factory'

    App\Messaging\Consumer\MessagingConsumer:
        arguments:
            $sqsClient: '@aws_sqs_client'
            $queueUrl: '%env(AWS_SQS_URL_ARN)%'

    App\Messaging\Dispatcher\MessagingDispatcher:
        arguments:
            $snsClient: '@aws_sns_client'
            $topicArn: '%env(AWS_SNS_TOPIC_ARN)%'

    guzzle.broadcaster.client:
        class: 'GuzzleHttp\Client'
        arguments:
            - timeout: 30

    App\Service\Api\BroadcastApiService:
        arguments:
            $client: '@guzzle.broadcaster.client'